### ISSUE TITLE
env.py in tests folder

### ISSUE THREAD

**Issue by Kadafimuamar** [mind-network/mind-lake-sdk-python#8]
there have no gateway
you must add gateway in env

**Comment by dennis-mind** [comment]
Thanks a lot for the feedback. We've updated all the tests and fixed the bug. There's no need for GATEWAY in env now.
Please pull the code and run the tests again, and check whether the problem is solved. Thanks.

**Comment by Kadafimuamar** [comment]
Thank you.

**Comment by dennis-mind** [comment]
Close as the problem solved.
